# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_table_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 601)
        MainWindow.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.tabla_peliculas = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_peliculas.setGeometry(QtCore.QRect(20, 70, 1001, 491))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabla_peliculas.setFont(font)
        self.tabla_peliculas.setStyleSheet("font: 12pt \"Comic Sans MS\";")
        self.tabla_peliculas.setObjectName("tabla_peliculas")
        self.tabla_peliculas.setColumnCount(10)
        self.tabla_peliculas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla_peliculas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_peliculas.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        item.setFont(font)
        self.tabla_peliculas.setHorizontalHeaderItem(9, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LISTADO DE PELÍCULAS:"))
        item = self.tabla_peliculas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tabla_peliculas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Título"))
        item = self.tabla_peliculas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Duración"))
        item = self.tabla_peliculas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Género"))
        item = self.tabla_peliculas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sinopsis"))
        item = self.tabla_peliculas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Valoración"))
        item = self.tabla_peliculas.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Vista"))
        item = self.tabla_peliculas.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Detalles"))
        item = self.tabla_peliculas.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Editar"))
        item = self.tabla_peliculas.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Borrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
