# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 404)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_introduce_euros = QtWidgets.QLabel(self.centralwidget)
        self.label_introduce_euros.setGeometry(QtCore.QRect(130, 10, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_introduce_euros.setFont(font)
        self.label_introduce_euros.setObjectName("label_introduce_euros")
        self.entrada_euros = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_euros.setGeometry(QtCore.QRect(200, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.entrada_euros.setFont(font)
        self.entrada_euros.setObjectName("entrada_euros")
        self.boton_convertir_dolares = QtWidgets.QPushButton(self.centralwidget)
        self.boton_convertir_dolares.setGeometry(QtCore.QRect(80, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_convertir_dolares.setFont(font)
        self.boton_convertir_dolares.setObjectName("boton_convertir_dolares")
        self.boton_convertir_bolivares = QtWidgets.QPushButton(self.centralwidget)
        self.boton_convertir_bolivares.setGeometry(QtCore.QRect(80, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_convertir_bolivares.setFont(font)
        self.boton_convertir_bolivares.setObjectName("boton_convertir_bolivares")
        self.resultado_dolares = QtWidgets.QLabel(self.centralwidget)
        self.resultado_dolares.setGeometry(QtCore.QRect(260, 140, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.resultado_dolares.setFont(font)
        self.resultado_dolares.setText("")
        self.resultado_dolares.setObjectName("resultado_dolares")
        self.resultado_bolivares = QtWidgets.QLabel(self.centralwidget)
        self.resultado_bolivares.setGeometry(QtCore.QRect(260, 260, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.resultado_bolivares.setFont(font)
        self.resultado_bolivares.setText("")
        self.resultado_bolivares.setObjectName("resultado_bolivares")
        self.resultado_libras = QtWidgets.QLabel(self.centralwidget)
        self.resultado_libras.setGeometry(QtCore.QRect(260, 300, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.resultado_libras.setFont(font)
        self.resultado_libras.setText("")
        self.resultado_libras.setObjectName("resultado_libras")
        self.boton_convertir_libras = QtWidgets.QPushButton(self.centralwidget)
        self.boton_convertir_libras.setGeometry(QtCore.QRect(80, 300, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_convertir_libras.setFont(font)
        self.boton_convertir_libras.setObjectName("boton_convertir_libras")
        self.resultado_francos = QtWidgets.QLabel(self.centralwidget)
        self.resultado_francos.setGeometry(QtCore.QRect(260, 220, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.resultado_francos.setFont(font)
        self.resultado_francos.setText("")
        self.resultado_francos.setObjectName("resultado_francos")
        self.boton_convertir_yenes = QtWidgets.QPushButton(self.centralwidget)
        self.boton_convertir_yenes.setGeometry(QtCore.QRect(80, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_convertir_yenes.setFont(font)
        self.boton_convertir_yenes.setObjectName("boton_convertir_yenes")
        self.boton_convertir_francos = QtWidgets.QPushButton(self.centralwidget)
        self.boton_convertir_francos.setGeometry(QtCore.QRect(80, 220, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_convertir_francos.setFont(font)
        self.boton_convertir_francos.setObjectName("boton_convertir_francos")
        self.resultado_yenes = QtWidgets.QLabel(self.centralwidget)
        self.resultado_yenes.setGeometry(QtCore.QRect(260, 180, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.resultado_yenes.setFont(font)
        self.resultado_yenes.setText("")
        self.resultado_yenes.setObjectName("resultado_yenes")
        self.usa = QtWidgets.QLabel(self.centralwidget)
        self.usa.setGeometry(QtCore.QRect(30, 130, 41, 41))
        self.usa.setStyleSheet("border-image: url(ventanas/images/USA.png);")
        self.usa.setText("")
        self.usa.setObjectName("usa")
        self.japon = QtWidgets.QLabel(self.centralwidget)
        self.japon.setGeometry(QtCore.QRect(30, 170, 41, 41))
        self.japon.setStyleSheet("border-image: url(ventanas/images/JP.png);")
        self.japon.setText("")
        self.japon.setObjectName("japon")
        self.eu = QtWidgets.QLabel(self.centralwidget)
        self.eu.setGeometry(QtCore.QRect(350, 60, 51, 51))
        self.eu.setStyleSheet("border-image: url(ventanas/images/UE2.png);")
        self.eu.setText("")
        self.eu.setObjectName("eu")
        self.uk = QtWidgets.QLabel(self.centralwidget)
        self.uk.setGeometry(QtCore.QRect(30, 290, 41, 41))
        self.uk.setStyleSheet("border-image: url(ventanas/images/UK.png);")
        self.uk.setText("")
        self.uk.setObjectName("uk")
        self.suiza = QtWidgets.QLabel(self.centralwidget)
        self.suiza.setGeometry(QtCore.QRect(30, 210, 41, 41))
        self.suiza.setStyleSheet("border-image: url(ventanas/images/SZ.png);")
        self.suiza.setText("")
        self.suiza.setObjectName("suiza")
        self.vzla = QtWidgets.QLabel(self.centralwidget)
        self.vzla.setGeometry(QtCore.QRect(30, 250, 41, 41))
        self.vzla.setStyleSheet("border-image: url(ventanas/images/VZLA.png);")
        self.vzla.setText("")
        self.vzla.setObjectName("vzla")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_introduce_euros.setText(_translate("MainWindow", "Introduce una cantidad en euros:"))
        self.boton_convertir_dolares.setText(_translate("MainWindow", "Convertir a Dólares:"))
        self.boton_convertir_bolivares.setText(_translate("MainWindow", "Convertir a Bolívares:"))
        self.boton_convertir_libras.setText(_translate("MainWindow", "Convertir a Libras:"))
        self.boton_convertir_yenes.setText(_translate("MainWindow", "Convertir a Yenes:"))
        self.boton_convertir_francos.setText(_translate("MainWindow", "Convertir a Fancos:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
