# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HeladeriaDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class HeladeriaDialog(object):
    def setupUi(self, HeladeriaDialog):
        HeladeriaDialog.setObjectName("HeladeriaDialog")
        HeladeriaDialog.resize(320, 290)
        font = QtGui.QFont()
        font.setPointSize(11)
        HeladeriaDialog.setFont(font)
        self.label = QtWidgets.QLabel(HeladeriaDialog)
        self.label.setGeometry(QtCore.QRect(120, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(HeladeriaDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(HeladeriaDialog)
        self.label_3.setGeometry(QtCore.QRect(180, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gbx_helados = QtWidgets.QGroupBox(HeladeriaDialog)
        self.gbx_helados.setGeometry(QtCore.QRect(20, 70, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gbx_helados.setFont(font)
        self.gbx_helados.setCheckable(True)
        self.gbx_helados.setObjectName("gbx_helados")
        self.chk_chocolate = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_chocolate.setGeometry(QtCore.QRect(10, 20, 121, 17))
        self.chk_chocolate.setObjectName("chk_chocolate")
        self.chk_vainilla = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_vainilla.setGeometry(QtCore.QRect(10, 50, 111, 17))
        self.chk_vainilla.setObjectName("chk_vainilla")
        self.chk_nata = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_nata.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.chk_nata.setObjectName("chk_nata")
        self.chk_fresa = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_fresa.setGeometry(QtCore.QRect(10, 110, 101, 17))
        self.chk_fresa.setObjectName("chk_fresa")
        self.gbx_bebidas = QtWidgets.QGroupBox(HeladeriaDialog)
        self.gbx_bebidas.setGeometry(QtCore.QRect(180, 70, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gbx_bebidas.setFont(font)
        self.gbx_bebidas.setCheckable(True)
        self.gbx_bebidas.setObjectName("gbx_bebidas")
        self.chk_cafe = QtWidgets.QCheckBox(self.gbx_bebidas)
        self.chk_cafe.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.chk_cafe.setObjectName("chk_cafe")
        self.chk_agua = QtWidgets.QCheckBox(self.gbx_bebidas)
        self.chk_agua.setGeometry(QtCore.QRect(10, 50, 101, 17))
        self.chk_agua.setObjectName("chk_agua")
        self.chk_cocacola = QtWidgets.QCheckBox(self.gbx_bebidas)
        self.chk_cocacola.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.chk_cocacola.setObjectName("chk_cocacola")
        self.lbl_total = QtWidgets.QLabel(HeladeriaDialog)
        self.lbl_total.setGeometry(QtCore.QRect(30, 220, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_total.setFont(font)
        self.lbl_total.setText("")
        self.lbl_total.setObjectName("lbl_total")

        self.retranslateUi(HeladeriaDialog)
        QtCore.QMetaObject.connectSlotsByName(HeladeriaDialog)

    def retranslateUi(self, HeladeriaDialog):
        _translate = QtCore.QCoreApplication.translate
        HeladeriaDialog.setWindowTitle(_translate("HeladeriaDialog", "Heladería"))
        self.label.setText(_translate("HeladeriaDialog", "Menú"))
        self.label_2.setText(_translate("HeladeriaDialog", "Elige tu helado:"))
        self.label_3.setText(_translate("HeladeriaDialog", "Elige tu bebida:"))
        self.gbx_helados.setTitle(_translate("HeladeriaDialog", "Helados"))
        self.chk_chocolate.setText(_translate("HeladeriaDialog", "Chocolate 3 euros"))
        self.chk_vainilla.setText(_translate("HeladeriaDialog", "Vainilla 2 euros"))
        self.chk_nata.setText(_translate("HeladeriaDialog", "Nata 2 euros"))
        self.chk_fresa.setText(_translate("HeladeriaDialog", "Fresa 2 euros"))
        self.gbx_bebidas.setTitle(_translate("HeladeriaDialog", "Bebidas"))
        self.chk_cafe.setText(_translate("HeladeriaDialog", "Café 2 euros"))
        self.chk_agua.setText(_translate("HeladeriaDialog", "Agua 1 euro"))
        self.chk_cocacola.setText(_translate("HeladeriaDialog", "CocaCola 2 euros"))
